spring:
  application:
    name: digital-bank-api
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    driver-class-name: org.postgresql.Driver
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
